# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/100-days-dl',
                'doc_host': 'https://achinta.github.io',
                'git_url': 'https://github.com/achinta/100-days-dl',
                'lib_path': '100_days_dl'},
  'syms': {'100_days_dl.core': {'100_days_dl.core.foo': ('core.html#foo', '100_days_dl/core.py')}}}
