# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['ResidualBlock']

# %% ../../nbs/00_core.ipynb 3
import torch
import torch.nn as nn

# display images
from IPython.display import Image, display
import torchvision
from torchview import draw_graph



class ResidualBlock(nn.Module):
    '''residual block '''
    def __init__(self, 
                 in_channels: int,
                 out_channels: int,
                 stride: int = 1,
                 downsample: nn.Module = None):
        super().__init__()
